//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdelaideFuel.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AdelaideFuel.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CacheData {
            get {
                return ResourceManager.GetString("CacheData", resourceCulture);
            }
        }
        
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string FeedbackSubjectItem {
            get {
                return ResourceManager.GetString("FeedbackSubjectItem", resourceCulture);
            }
        }
        
        public static string GenerateTestCrash {
            get {
                return ResourceManager.GetString("GenerateTestCrash", resourceCulture);
            }
        }
        
        public static string ItemDashItem {
            get {
                return ResourceManager.GetString("ItemDashItem", resourceCulture);
            }
        }
        
        public static string ItemToItem {
            get {
                return ResourceManager.GetString("ItemToItem", resourceCulture);
            }
        }
        
        public static string LogSize {
            get {
                return ResourceManager.GetString("LogSize", resourceCulture);
            }
        }
        
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string PleaseRateSif {
            get {
                return ResourceManager.GetString("PleaseRateSif", resourceCulture);
            }
        }
        
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string OpenAppSettings {
            get {
                return ResourceManager.GetString("OpenAppSettings", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string ItemSpaceItem {
            get {
                return ResourceManager.GetString("ItemSpaceItem", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        public static string Attributions {
            get {
                return ResourceManager.GetString("Attributions", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string ItemParenthesesItem {
            get {
                return ResourceManager.GetString("ItemParenthesesItem", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string UnableToLoadStations {
            get {
                return ResourceManager.GetString("UnableToLoadStations", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        public static string OpenAppSettingsDescription {
            get {
                return ResourceManager.GetString("OpenAppSettingsDescription", resourceCulture);
            }
        }
        
        public static string SendFeedbackDescription {
            get {
                return ResourceManager.GetString("SendFeedbackDescription", resourceCulture);
            }
        }
        
        public static string FromItem {
            get {
                return ResourceManager.GetString("FromItem", resourceCulture);
            }
        }
        
        public static string FromItemToItem {
            get {
                return ResourceManager.GetString("FromItemToItem", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        public static string AddYourMessageBelow {
            get {
                return ResourceManager.GetString("AddYourMessageBelow", resourceCulture);
            }
        }
        
        public static string ItemComma {
            get {
                return ResourceManager.GetString("ItemComma", resourceCulture);
            }
        }
        
        public static string ItemCommaItem {
            get {
                return ResourceManager.GetString("ItemCommaItem", resourceCulture);
            }
        }
        
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        public static string EmailDirectly {
            get {
                return ResourceManager.GetString("EmailDirectly", resourceCulture);
            }
        }
        
        public static string UnableToSendEmail {
            get {
                return ResourceManager.GetString("UnableToSendEmail", resourceCulture);
            }
        }
        
        public static string ShouldIFuel {
            get {
                return ResourceManager.GetString("ShouldIFuel", resourceCulture);
            }
        }
        
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        public static string Fuels {
            get {
                return ResourceManager.GetString("Fuels", resourceCulture);
            }
        }
        
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string TwentyFourHours {
            get {
                return ResourceManager.GetString("TwentyFourHours", resourceCulture);
            }
        }
        
        public static string CheapestInItem {
            get {
                return ResourceManager.GetString("CheapestInItem", resourceCulture);
            }
        }
        
        public static string ItemKm {
            get {
                return ResourceManager.GetString("ItemKm", resourceCulture);
            }
        }
        
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        public static string CheapestAndClosestInItem {
            get {
                return ResourceManager.GetString("CheapestAndClosestInItem", resourceCulture);
            }
        }
        
        public static string BrandsDescription {
            get {
                return ResourceManager.GetString("BrandsDescription", resourceCulture);
            }
        }
        
        public static string FuelsDescription {
            get {
                return ResourceManager.GetString("FuelsDescription", resourceCulture);
            }
        }
        
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        public static string MustHaveAtLeastOneActiveItem {
            get {
                return ResourceManager.GetString("MustHaveAtLeastOneActiveItem", resourceCulture);
            }
        }
        
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        public static string UnableToLoadBrands {
            get {
                return ResourceManager.GetString("UnableToLoadBrands", resourceCulture);
            }
        }
        
        public static string UnableToLoadFuels {
            get {
                return ResourceManager.GetString("UnableToLoadFuels", resourceCulture);
            }
        }
        
        public static string UnableToLoadPrices {
            get {
                return ResourceManager.GetString("UnableToLoadPrices", resourceCulture);
            }
        }
        
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        public static string SaBowser {
            get {
                return ResourceManager.GetString("SaBowser", resourceCulture);
            }
        }
        
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        public static string FuelSetup {
            get {
                return ResourceManager.GetString("FuelSetup", resourceCulture);
            }
        }
        
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        public static string NoPricesDescription {
            get {
                return ResourceManager.GetString("NoPricesDescription", resourceCulture);
            }
        }
        
        public static string NoStationsFound {
            get {
                return ResourceManager.GetString("NoStationsFound", resourceCulture);
            }
        }
        
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        public static string ReportPriceError {
            get {
                return ResourceManager.GetString("ReportPriceError", resourceCulture);
            }
        }
        
        public static string Radii {
            get {
                return ResourceManager.GetString("Radii", resourceCulture);
            }
        }
        
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        public static string RadiiDescription {
            get {
                return ResourceManager.GetString("RadiiDescription", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string EnterNewRadius {
            get {
                return ResourceManager.GetString("EnterNewRadius", resourceCulture);
            }
        }
        
        public static string Kilometres {
            get {
                return ResourceManager.GetString("Kilometres", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string RestoreDefaultSettings {
            get {
                return ResourceManager.GetString("RestoreDefaultSettings", resourceCulture);
            }
        }
        
        public static string OnDataProvidedBySaGovCurrentYearItem {
            get {
                return ResourceManager.GetString("OnDataProvidedBySaGovCurrentYearItem", resourceCulture);
            }
        }
        
        public static string InformationForMotorists {
            get {
                return ResourceManager.GetString("InformationForMotorists", resourceCulture);
            }
        }
        
        public static string SaFuelPricingScheme {
            get {
                return ResourceManager.GetString("SaFuelPricingScheme", resourceCulture);
            }
        }
        
        public static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string OosFuels {
            get {
                return ResourceManager.GetString("OosFuels", resourceCulture);
            }
        }
        
        public static string NoLocationWarning {
            get {
                return ResourceManager.GetString("NoLocationWarning", resourceCulture);
            }
        }
        
        public static string ShowRadiiOnMap {
            get {
                return ResourceManager.GetString("ShowRadiiOnMap", resourceCulture);
            }
        }
        
        public static string SubscriptionDescription {
            get {
                return ResourceManager.GetString("SubscriptionDescription", resourceCulture);
            }
        }
        
        public static string RestorePreviousPurchases {
            get {
                return ResourceManager.GetString("RestorePreviousPurchases", resourceCulture);
            }
        }
        
        public static string ChangeOrCancelSubscription {
            get {
                return ResourceManager.GetString("ChangeOrCancelSubscription", resourceCulture);
            }
        }
        
        public static string BannerAds {
            get {
                return ResourceManager.GetString("BannerAds", resourceCulture);
            }
        }
        
        public static string AppleSubscriptionDisclaimer {
            get {
                return ResourceManager.GetString("AppleSubscriptionDisclaimer", resourceCulture);
            }
        }
        
        public static string CannotConnectStore {
            get {
                return ResourceManager.GetString("CannotConnectStore", resourceCulture);
            }
        }
        
        public static string ItemPerYear {
            get {
                return ResourceManager.GetString("ItemPerYear", resourceCulture);
            }
        }
        
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        public static string GoogleSubscriptionDisclaimer {
            get {
                return ResourceManager.GetString("GoogleSubscriptionDisclaimer", resourceCulture);
            }
        }
        
        public static string SubscriptionThankyou {
            get {
                return ResourceManager.GetString("SubscriptionThankyou", resourceCulture);
            }
        }
        
        public static string BannerAdsDescription {
            get {
                return ResourceManager.GetString("BannerAdsDescription", resourceCulture);
            }
        }
        
        public static string ControlAdsSupportDevelopment {
            get {
                return ResourceManager.GetString("ControlAdsSupportDevelopment", resourceCulture);
            }
        }
        
        public static string ShouldIFuelPremium {
            get {
                return ResourceManager.GetString("ShouldIFuelPremium", resourceCulture);
            }
        }
        
        public static string GoToSubscription {
            get {
                return ResourceManager.GetString("GoToSubscription", resourceCulture);
            }
        }
        
        public static string SubscriptionActiveUntilFormat {
            get {
                return ResourceManager.GetString("SubscriptionActiveUntilFormat", resourceCulture);
            }
        }
        
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        public static string SubscriptionExpiredDescription {
            get {
                return ResourceManager.GetString("SubscriptionExpiredDescription", resourceCulture);
            }
        }
        
        public static string SubscriptionExpiredOnFormat {
            get {
                return ResourceManager.GetString("SubscriptionExpiredOnFormat", resourceCulture);
            }
        }
        
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        public static string IssueOpeningUrlItem {
            get {
                return ResourceManager.GetString("IssueOpeningUrlItem", resourceCulture);
            }
        }
        
        public static string CrashingSubjectItem {
            get {
                return ResourceManager.GetString("CrashingSubjectItem", resourceCulture);
            }
        }
        
        public static string AdInspector {
            get {
                return ResourceManager.GetString("AdInspector", resourceCulture);
            }
        }
    }
}
