name: Build MAUI Project

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: "com.dgatto.adelaidefuel"
  PROJECT_FOLDER: "src/App/AdelaideFuel.Maui"
  PROJECT_FILE: "src/App/AdelaideFuel.Maui/AdelaideFuel.Maui.csproj"
  PROJECT_NAME: "AdelaideFuel"
  DOTNET_VERSION: 9.0.x  
  DOTNET_VERSION_TARGET: net9.0
  DOTNET_WORKLOAD_VERSION: 9.0.100
  XCODE_VERSION: 16.2

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      packageName: ${{ env.PACKAGE_NAME }} 
      projectFolder: ${{ env.PROJECT_FOLDER }} 
      projectFile: ${{ env.PROJECT_FILE }}
      projectName: ${{ env.PROJECT_NAME }}
      dotnetVersion: ${{ env.DOTNET_VERSION }}
      dotnetVersionTarget: ${{ env.DOTNET_VERSION_TARGET }}
      dotnetWorkloadVersion: ${{ env.DOTNET_WORKLOAD_VERSION }}
      xcodeVersion: ${{ env.XCODE_VERSION }} 
    steps:
      - run: echo "Exposing env vars, because they can't be passed to nested workflows."


  build-ios:
    needs: vars 
    uses: ./.github/workflows/cd-ios.yml
    with:
      package-name: ${{ needs.vars.outputs.packageName }}
      project-folder: ${{ needs.vars.outputs.projectFolder }}
      project-file: ${{ needs.vars.outputs.projectFile }}
      project-name: ${{ needs.vars.outputs.projectName }}
      dotnet-version: ${{ needs.vars.outputs.dotnetVersion }}
      dotnet-version-target: ${{ needs.vars.outputs.dotnetVersionTarget }}
      dotnet-workload-version: ${{ needs.vars.outputs.dotnetWorkloadVersion }}
      xcode-version: ${{ needs.vars.outputs.xcodeVersion }}
      build-config: 'Release'
      build-number: ${{ github.run_number }}
      build-offset: ${{ vars.IOS_BUILD_OFFSET }}
    secrets:
      p12-cert: ${{ secrets.IOS_P12_B64 }}
      p12-cert-password: ${{ secrets.IOS_P12_PASSWORD }}
      appstore-issuer: ${{ secrets.APPSTORE_ISSUER_ID }}
      appstore-keyid: ${{ secrets.APPSTORE_KEY_ID }}
      appstore-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      settings-json: ${{ secrets.IOS_SETTINGS_JSON }}
      admob-app-id: ${{ secrets.IOS_ADMOB_APPLICATION_ID }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN  }}
      sentry-org: ${{ secrets.SENTRY_ORG  }}
      sentry-project: ${{ secrets.SENTRY_PROJECT  }}

  build-droid:
    needs: vars 
    uses: ./.github/workflows/cd-droid.yml
    with:
      package-name: ${{ needs.vars.outputs.packageName }}
      project-folder: ${{ needs.vars.outputs.projectFolder }}
      project-file: ${{ needs.vars.outputs.projectFile }}
      project-name: ${{ needs.vars.outputs.projectName }}
      dotnet-version: ${{ needs.vars.outputs.dotnetVersion }}
      dotnet-version-target: ${{ needs.vars.outputs.dotnetVersionTarget }}
      dotnet-workload-version: ${{ needs.vars.outputs.dotnetWorkloadVersion }}
      build-config: 'Release'
      build-number: ${{ github.run_number }}
      build-offset: ${{ vars.DROID_BUILD_OFFSET }}
    secrets:
      keystore: ${{ secrets.DROID_KEYSTORE_B64 }}
      keystore-password: ${{ secrets.DROID_KEYSTORE_PW }}
      keystore-alias: ${{ secrets.DROID_KEYSTORE_ALIAS }}
      keystore-key-password: ${{ secrets.DROID_KEYSTORE_KEY_PW }}
      playstore-service-account: ${{ secrets.PLAYSTORE_SERVICE_ACC }}
      settings-json: ${{ secrets.DROID_SETTINGS_JSON }}
      admob-app-id: ${{ secrets.DROID_ADMOB_APPLICATION_ID }}
      google-maps-api-key: ${{ secrets.DROID_GOOGLE_MAPS_API_KEY }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN  }}
      sentry-org: ${{ secrets.SENTRY_ORG  }}
      sentry-project: ${{ secrets.SENTRY_PROJECT  }}
